<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RealTimePortal.Application\RealTimePortal.Application.csproj" />
    <ProjectReference Include="..\RealTimePortal.Domain\RealTimePortal.Domain.csproj" />
    <ProjectReference Include="..\RealTimePortal.Infrastructure\RealTimePortal.Infrastructure.csproj" />
  </ItemGroup>

</Project>
